repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        files: \.yml$

      - id: check-yaml
        args: [ --unsafe ]
        files: \.yml$


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.2
    hooks:
      
      # Run the linter.
      - id: ruff
        language_version: python3.8
        files: src/.*\.py$
        
        
        # Run the formatter.
      - id: ruff-format
        language_version: python3.8
        files: src/.*\.py$
        
